version: "3.8"

services:
    mydb:
        image: postgres
        volumes:
            - pSql:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: sample
        ports:
            - "5432:5432"
        networks:
            - fine

    backend:
        image: elektraverse/back
        build: "./server"
        container_name: back_end
        environment: 
            - NODE_ENV=development
        depends_on:
            - mydb
        ports:
            - "4000:4000"
        networks:
            - fine
        volumes:
            - ./server/:/usr/src/app
            - /usr/src/app/node_modules

networks:
    fine:

volumes:
    pSql:
